import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notification events
self.addEventListener('push', (event) => {
    if (!event.data) return

    try {
        const data = event.data.json()
        const options = {
            body: data.notification.body,
            icon: '/logo-default.svg',
            badge: '/logo-default.svg',
            data: {
                url: data.notification.data?.url || '/'
            }
        }

        event.waitUntil(
            self.registration.showNotification(data.notification.title, options)
        )
    } catch (err) {
        console.error('Push event error:', err)
    }
})

// Handle notification click event
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window open with this URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i]
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus()
                }
            }
            // If no window found, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen)
            }
        })
    )
})
