import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notification handler ──────────────────────────────────────────────
self.addEventListener('push', (event) => {
    if (!event.data) return

    let title = 'Yeni Bildirim'
    let body  = ''
    let url   = '/notifications'

    try {
        const payload = event.data.json()
        // Support {notification:{title,body,data}} and flat {title,body,data} formats
        const notif = payload.notification ?? payload
        title = notif.title   ?? payload.title   ?? title
        body  = notif.body    ?? notif.message   ?? payload.body ?? payload.message ?? body
        url   = notif.data?.url ?? payload.data?.url ?? url
    } catch {
        // Backend might send plain text
        body = event.data.text() || body
    }

    event.waitUntil(
        self.registration.showNotification(title, {
            body,
            icon:             '/logo-default.svg',
            badge:            '/logo-default.svg',
            vibrate:          [200, 100, 200],
            requireInteraction: false,
            data:             { url },
        })
    )
})

// ── Notification click handler ─────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const targetUrl = new URL(
        event.notification.data?.url ?? '/notifications',
        self.location.origin
    ).href

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Find any open window from our app
            const appWindow = windowClients.find(c =>
                c.url.startsWith(self.location.origin)
            )
            if (appWindow) {
                // Focus the window and navigate it to the target URL
                return appWindow.focus().then(c => c.navigate(targetUrl))
            }
            // No open window — open a new one
            return clients.openWindow(targetUrl)
        })
    )
})
